### ISSUE TITLE
v2.1 ToDo

### ISSUE THREAD

**Issue by dantrueman** [Princeton-CDH/bitKlavier#102]
- [ ] Undo/Redo (this could be tough, but im finally wrapping my head around good ways to do it)
- [ ] iCloud integration; https://forum.juce.com/t/native-ios-android-file-choosers/25206
- [ ] multiple versions of the same sPrep open in a single Piano?
- [ ] Option to display preparation name or little bits of info about preparations in graph
-------------
- [ ] Generic sample loading using soundfonts (sfz)
- [ ] Scripting
- [ ] Ableton Link
