### ISSUE TITLE
MIKE TODO

### ISSUE THREAD

**Issue by mulshine** [Princeton-CDH/bitKlavier#116]
- [ ] Make more production/improvisation galleries
- [ ] read papers (check out tempo section)
- [ ] Spring tuning mods
- [ ] tempo copy paste (new param subdivision may have messed this up)
- [ ] soundfont bug where synchronic notes don't trigger (in looped samples)
- [x] undertow notes don't cut off (gracefully) when key-on reset is enabled 
- [x] Rework mods ( and IDs hash ? )
- [x] Add to list of possible new feature while doing above ^
- [x] Make multiple windows/tabs (arrows) for preparations 
- [x] modification triggered by only one note in keymap bug (describer better by dan in another issue)
- [x] Nostalgic cluster min/max, hold min/max, reset/off (full and per-key)
-------------
- [ ] Linux ? Email Nicholas Shaheed <nicholasshaheed@gmail.com>
-------------
- [ ] UNDO / REDO
- [ ] ATTACH / REATTACH CABLES
