### ISSUE TITLE
Direct ToDo

### ISSUE THREAD

**Issue by mulshine** [Princeton-CDH/bitKlavier#28]
- [x] overlay
- [x] integrate transposition with Tuning
- [x] gain
- [x] merged with Main, so Direct becomes Main
- [ ] rename Direct as Main?
- [ ] resonance and hammer? have a toggle on each layer whether to trigger them or not, by default of this toggle on for layer 1 and off for all the other layers.

- [ ] will layers cause sounding notes to cut-off, if they use the same sample? need to check. similar to issue with Synchronic.
