### ISSUE TITLE
Tuning ToDo

### ISSUE THREAD

**Issue by dantrueman** [Princeton-CDH/bitKlavier#29]
- [x] Implement TuningPreparation class, pass pointer to S/N processors

- [x] Implement Adaptive Tuning functionality

- [x] adjust and complete GUI to fully test, with all Tuning params

- [ ] fix adaptive

- [ ] implement custom scale
