### ISSUE TITLE
Mike ToDo

### ISSUE THREAD

**Issue by mulshine** [Princeton-CDH/bitKlavier#33]
**UI**
- [ ] Preparation names, dropdown menu for selection
- [ ] Keymap keyboard toggle (BKKeymapComponent, BKKeymapState, BKKeyboardComponent, BKKeyboardState)
- [x] Piano Construction Site UI 
- [ ] Toggle 

**Presets (after parameter keymap)**
- [ ] Reading / Writing  (Preset/Library/Files)

**Other**
- [ ] Basic scripting math
- [ ] External controller input for parameters
