### ISSUE TITLE
Dan ToDo

### ISSUE THREAD

**Issue by dantrueman** [Princeton-CDH/bitKlavier#34]
- [x] basic documentation for beta-testers; google doc that some of them can edit
- [x] test test test... both playing directly and embedding in Sibelius to reproduce Etudes and Mikroetudes
- [x] create clean bitKlavier_examples, and NostalgicSynchronic galleries
- [x] forum, initially for beta-testers; forum hosting sites?
- [ ] import/export individual preparations
- [ ] add global gains for Direct, Nostalgic, Synchronic to General Settings
-----
- [ ] resizing doesn't work properly with Standalone on my laptop; works ok for Mike, and also on my iMac
- [ ] titlebar color!!! not addressable in plugin, but possibly in standalone; might have to put Options button functionality elsewhere
- [ ] splash screen for standalone
-----
- [ ] envelopes for Synchronic, others?
- [ ] implement "relative to tuning" transposition in all preparations
- [ ] implement pedal down and up samples
- [ ] Plugin automation? going to be tricky, since the available params are so dynamic, depending on the Gallery/Piano configuration. this may be best to wait for a later version
- [x] transposition bug; 037 in Direct, for example, lots of dropped notes. related to minor-3rd separation of sample library?
- [x] tuning names are not being saved to XML
- [x] Marbles behavior is not quite right; notes are not sustained long enough in the pulses.
- [x] tempo note-length mode not getting set properly
- [x] tempo reset button not working
- [x] figure out what is going on with Nostalgic sync mode when Synchronic is in anything other than First Note-On 
- [x] single click on Nostalgic trans slider doesn't change value unless close to slider. helps with double=click
- [x] Synchronic transpositions; add new with value near click, and background alpha with multiple transpose
- [x] General Settings: only really need tuning reference (440) and tempo multiplier
- [x] click-away issues in Preps; want to be able to click outside and have it go away. also click INSIDE and have Texteditors lose focus
- [x] default tempo on gallery load
- [x] "clear mods" button in Mods UI
- [x] UI for Mods
- [x] hide noteOff Loudness
- [x] dropShadow for construction site?
- [x] transposition sub slider stuff in Synchronic
- [x] keymap keyboard; select multiples by drag... also for playback in the bottom keyboard
- [x] bKeditableComboBox crash; click on arrow, then menu
- [x] Synchronic gain slider not doing anything
- [x] KeyMapVC
- [x] sustain pedal not working properly with preps; they start with keyUps, regardless of what pedal is doing
- [x] work up rough UIs for all preparations
- [x] test json loading and old presets
- [x] UI mockups of preparation windows, modifications windows, and related
- [x] work on transposition issue when preparation changes while key is down
- [x] Tempo Preparation; create, extract from Synchronic
- [x] Plugin host saving/loading Presets
- [x] reset keymap implement storage/loading, but not resetkeymap mod, which is just perverse
- [x] reset keymap, within preparations; specific keys copy static to active and reset internal params like adaptiveTempoMult and adaptiveTuningFundamental
- [x] implement modifications for Absolute tuning
- [x] Heavy nostalgic clicks
- [x] accent/gain vals > 1 in Synchronic not working
- [x] mockup UI for Modifications, with new single-key assignments
- [x] absolute tuning; offset for any particular note(s) (64:-13.7, etc...); add UI for that
- [x] custom tuning with arbitrary number of offsets; rotating tuning. main question: which octave does the fundamental apply to? the lowest?
- [x] implement adaptive tempo
- [x] global tempoMultiplier
- [x] global tuning fundamental
- [x] is synchronic tracking velocity to set loudness of pulses? need to implement
- [x] same question for nostalgic; seems not... fixed.
- [x] modify Max mockups (wrapping preps/pianos into menus), refine
- [x] fix adaptive tuning
- [x] implement custom tuning
- [x] implement direct toggle for resonance and hammer
- [x] repeated notes => clicks with resonance/hammer; check into
- [x] edit hammer and resonance samples to make sure they don't have pre-sound silence.
- [x] check to see if Direct layers cause sounding notes to cut-off, if they use the same sample? need to check. similar to issue with Synchronic.
- [x] check to see if Transposition is being handled properly; we want to choose the closest sample after taking into account transposition
