### ISSUE TITLE
BETA TODO

### ISSUE THREAD

**Issue by mulshine** [Princeton-CDH/bitKlavier#51]
### Releases:
- [x] VST / AU / (AAX; possibly not for August 10)
- [x] Standalone OSX
- [x] cleanup sample folder so it only includes the 8 layers we're using
- [x] make git repository public

- [x] update README
- [x] have Master branch be beta-release
- [x] Development branch for pre-Master dev

### General:
- [x] basic documentation, short tutorial videos for beta-testers
- [x] galleries: examples, NS, Mike examples
- [x] save path so that next time you Open or Save As it goes to the same place as before
- [x] add prep popup to Gallery Action for adding preps (show equivalent keystrokes)
- [x] new blank gallery in Gallery Action
- [ ] short beta-Documentation/Manual 

### General:
- [ ] AAX
- [ ] import/export individual preparations
- [ ] RTAS
- [ ] VST3
- [ ] revisit Alert on quit with dirty gallery issue
- [x] eliminate keyboard alert sound issue

### Menus:
- [x] delete current preparation
- [x] copy current to new
- [x] menu organization 
- [ ] insert preparation before current
- [ ] moving items up/down; edit mode?

### Graph:
- [ ] basic undo / redo behavior
- [x] improve alignment tools
- [ ] delete patch cords
- [x] copy/pasting Synchronic (maybe others) within a Piano creates duplicate prep!
- [ ] scale construction area with resize and/or scroll bars
