### ISSUE TITLE
iOS ToDo

### ISSUE THREAD

**Issue by mulshine** [Princeton-CDH/bitKlavier#68]
- [x] Open/copy galleries to app from email/text/etc
- [x] Saving and loading gallery on device
- [x] File sharing via iTunes 
- [x] Splash screen
- [x] Slider touch opens text field (should not)
- [x] Custom number keypad (juce provides some, but none with brackets...)
- [x] Icon size scaling (based on screen size)
