### ISSUE TITLE
beta 2 todo

### ISSUE THREAD

**Issue by dantrueman** [Princeton-CDH/bitKlavier#83]
- [x] update Release on GIT to include all new features and changes.
- [x] LAF bug: seems to only apply for the ComboBoxes in HeaderViewController, and it's not clear if it has any real consequences (doesn't cause any crashes when using VST/Standalone in Release). only crashes on quit in Debug. but probably should change ComboBoxes to PopupMenus...
- [x] Gallery menu does not show name of chosen gallery if it's from a subfolder (external galleries; works ok for internal)
- [x] some of the minor ToDos from the class workshop; default values and so on...
- [x] VST state save/recall is not working for internal galleries
- [x] synchronic Mod multi-param fields bug
- [x] change default resonance value to much smaller; too loud as is
- [x] get Rename working for both Galleries and Pianos for iOS
- [x] remove undo/redo from Action menu (unless it's close; otherwise can save for b3)
- [x] wavedistance/undertow slider are broken in OS X; there is no way to enter vals as text and then get out -- pressing return/enter does nothing.
- [x] some cleanup of text alignment and so on (see Tuning window, for instance)
- [x] change sample library choice so that if one of the default piano libraries is loaded, it doesn't change when a new gallery is loaded (like the old behavior)
- [x] add octave slider to tuning keyboard
- [x] merge RK's README updates 
- [x] fix Gallery/Piano menu alignment in some way
- [x] finish sharing on iOS

**Comment by mulshine** [comment]
@dantrueman , have all these been completed?

**Comment by dantrueman** [comment]
other than the three that are unchecked, yes...
