### ISSUE TITLE
Pre-release features TODO

### ISSUE THREAD

**Issue by mulshine** [Princeton-CDH/bitKlavier#86]
**Top priorities:**
- [x] Splash screen + Progress bar https://juce.com/doc/classProgressBar#details
- [x] Comments 

**Later:**
- [ ] Undo/Redo (this could be tough, but im finally wrapping my head around good ways to do it)
- [ ] Option to display preparation name or little bits of info about preparations in graph
- [ ] Generic sample loading using soundfonts (sfz)

**Comment by dantrueman** [comment]
excellent. i can start work on this onFriday.



On December 13, 2017 at 2:39:50 PM, Mike Mulshine (notifications@github.com<mailto:notifications@github.com>) wrote:

  1.  Comments
  2.  Generic sample loading using soundfonts (sfz)
  3.  Option to display preparation name or little bits of info about preparations in graph
  4.  Undo/Redo (this could be tough, but im finally wrapping my head around good ways to do it)
